/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cc_sgqy_utils_cxx_OpenCC */

#ifndef _Included_cc_sgqy_utils_cxx_OpenCC
#define _Included_cc_sgqy_utils_cxx_OpenCC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cc_sgqy_utils_cxx_OpenCC
 * Method:    new_obj
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_cc_sgqy_utils_cxx_OpenCC_new_1obj
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cc_sgqy_utils_cxx_OpenCC
 * Method:    del_obj
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_cc_sgqy_utils_cxx_OpenCC_del_1obj
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cc_sgqy_utils_cxx_OpenCC
 * Method:    conv_text
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cc_sgqy_utils_cxx_OpenCC_conv_1text
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
